### ISSUE TITLE
How do I play default notification sound on android ?

### ISSUE THREAD

**Issue by sushrut-desora** [dashdoc/react-native-system-sounds#1]
I used "RNSystemSounds.iOSSoundIDs.SystemSoundPreview1" this constant to play notification sound in iOS. What constant should I use to play default notification sound (chime) on android ?

I looked through https://developer.android.com/reference/android/media/ToneGenerator#TONE_DTMF_0 but I could not determine the variable which refers to that sound

**Comment by Victorien-T** [comment]
Hello @sushrut-desora, sorry for the late reply.
Are you looking for `RNSystemSounds.AndroidSoundIDs.TONE_DTMF_0`?

**Comment by Victorien-T** [comment]
Well I'm pretty sure that this is what you were looking for so I close the issue.

**Comment by sushrut-desora** [comment]
Feel free to close the issue as this is not an actual issue with the library itself. However, "TONE_DTMF_0" tone is no where close to a chime sound nor is it suitable as a notification alert. We do not want our to play a long annoying beep for our users when they receive a notification or alert. I tried all the android constants and I believe that it might not be possible to play a chime notification sound using this library on android. It only work on iOS at the moment using "RNSystemSounds.iOSSoundIDs.SystemSoundPreview1" constant.

There was an error in the link attached to the issue. I am not looking for "TONE_DTMF_0". I was looking for a chime sound same as or similar to one you would play for a notification alert.

**Comment by Victorien-T** [comment]
Ok sorry to hear that, if you tried every sounds and none suits your needs there's not much we can do.
